### ISSUE TITLE
添加自动处理 Debian 安全通知（DSA）的功能

### ISSUE THREAD

**Issue by hosiet** [debiancn/debiancn-home#1]
如题。DSA 通知手动更新太累，不如自动化处理。

DSA 信息来源是确定的：https://www.debian.org/security/dsa 会返回一个合法 XML 文件，只需要对其解析即可。

**Comment by ocian** [comment]
好的 ，和剩下的两个页面一起做， 造一个一劳永逸的新轮子， 
还有一个 点击弹菜单的按钮。

如果有看到喜欢的，不错的，觉得加在我们页面上比较搭的，包括效果或者浏览器上面看得到的前端相关的东西都可以丢过来，我尽力做

**Comment by ocian** [comment]
debian news 
[Debian 计划新闻 https://www.debian.org/News/weekly/](https://www.debian.org/News/weekly/)  
确认一下， 可以的话把新闻和DSA通知都做成自动更新的

**Comment by hosiet** [comment]
还有这个来源也可以考虑选择： https://micronews.debian.org/

哪个方便用哪个。另外自动更新不可避免要写后端代码吧？不知道打算如何设计？纯前端跨站点加载内容会被浏览器挡下来的。

**Comment by ocian** [comment]
好像避不开后台代码，先把其他的写好把网页放上去吧，  
rss 的后台等我写完之后学习一下PHP，现在还是先修改html吧

**Comment by hosiet** [comment]
fixed via d11026f6030e6227e94e0155d67da1625c446af1.

实现方式：后端 wget 获取 XML 信息，然后做 XSLT 生成 index.html。
