### ISSUE TITLE
社区首页链接列表的跳转

### ISSUE THREAD

**Issue by ocian** [debiancn/debiancn-home#2]
安装指南可以使用 [debian 官方网站的 帮助文档](https://www.debian.org/releases/stable/amd64/index.html.zh-cn)
邮件列表 我打算放 [debian 官网的 邮件列表页](https://www.debian.org/releases/stable/amd64/index.html.zh-cn)
IRC频道是不是需要改一下名字叫fishroom或者聊天室[链接](https://irc.debiancn.org/log/debian-cn/today)
开发参与指南 博远的博客文章消失了， 我不会 debian 开发，博远把文章贡献出来吧， 我单独写成一页
代办事项 可以写到一个单独的页面里，然后要怎么更新呢
社区礼仪 要么就这个吧 [来自甘豆腐的帖子：提问前必读](https://forums.debiancn.org/viewtopic.php?f=11&t=145)

**Comment by hosiet** [comment]
邮件列表指向 [debian-chinese-gb](https://lists.debian.org/debian-chinese-gb) 比较好；开发参与可以直接指向 https://chinese.alioth.debian.org/cn 或者……等等，这个内容我没写过博客吧？用聊天室替换 irc 可行；待办事项为啥要写在主页上？

**Comment by ocian** [comment]
我不知道，但是现在的主页有代办事项，大概是想要链接到哪里吧
社区礼仪需要贴吗，如果没有的就隐藏掉了，有链接的时候再打开
在上面留空链接而且没有提示 不太好

**Comment by ocian** [comment]
首页右侧链接跳转页面看起来还可以
