### ISSUE TITLE
浏览器警告信息有问题

### ISSUE THREAD

**Issue by ghost** [debiancn/debiancn-home#3]
我的chrome也显示了那个ie警告

**Comment by ocian** [comment]
It's used to help you update the warning messeges. In the **'src/css/ls_index.css'** file with line:224, the `display: none;` can hide the IE warning messege. If someone use IE browser with version <= 8, the *'src/js/ls_script.js'* file can make the warning messege visiable, and add the click event to the close button to hide the warning messege

My fcitx can't work, so...

**Comment by ocian** [comment]
jQuery 2.x 版本开始放弃IE8 及以下浏览器支持，所以我写了一个永远也不会弹出来的警告信息🙈，
IE8下面和终端访问布局上看起来好像差不多，等等我把警告弹窗的删掉

**Comment by ocian** [comment]
已经去掉了
