### ISSUE TITLE
主页外观，超链接颜色和段落缩进

### ISSUE THREAD

**Issue by Yanhao** [debiancn/debiancn-home#4]
目前的蓝色超链接颜色和主页的整体颜色有点不搭配，比较难看，可以考虑换个颜色。
另外欢迎信息那个段落不缩进应该会更好。

**Comment by ocian** [comment]
颜色修正为 首页红色+0.8透明度，应该比较搭，
我本地推送出错，等下我把段落缩进去掉

**Comment by hosiet** [comment]
已上线，粉红颜色有点诡异啊

**Comment by Yanhao** [comment]
果然...我觉得我们还需要一个设计师

**Comment by ocian** [comment]
debian.org 的链接全部是没有修饰的天然蓝色

**Comment by Yanhao** [comment]
此讨论年代久远，关闭之
