### ISSUE TITLE
主页社区新闻的时间格式与Debian官方新闻显示的不一致

### ISSUE THREAD

**Issue by Yanhao** [debiancn/debiancn-home#5]
这个需要前端使用js进行一下转换。

**Comment by ocian** [comment]
newsTime 分之，修改自master分之，时间格式已经修正，另外和html标签里面原ing来的格式也用js修改过了，可以选一种格式保留；
删掉另外两个分之吧，应该没什么用处了

**Comment by hosiet** [comment]
完成。
