### ISSUE TITLE
首页改进建议收集

### ISSUE THREAD

**Issue by ocian** [debiancn/debiancn-home#6]
首页应该怎么做，收集意见，大概还有一两个月我就要换工作了，这中间应该有一段无所事是的时间，给自己开一个坑

现在的首页样式就是我写得，虽然我知道很难看，但是经验有限，自己写得比不上别人的框架demo好看，在这里列出我找到的一些样式组件库，请大家挑选，或者给出自己的建议
1. [Google's material-components-web](https://github.com/material-components/material-components-web) 好多人都喜欢这个，简略看过文档，用起来应该不难，文档和例子比较详细，我的弱点是我的英文不大好，但是对照 demo 看文档问题不大
2. [Semantic UI](https://semantic-ui.com/) 逛前端网站的时候偶然发现的，很符合 @ mo 的现代标准，看起来比较庞大
3. 如果有开源的 bootstrap 主题，比较适合 debian 的也可以推荐一下，bootstrap 在维护上面有一个文档简单的优势，感兴趣的程序员应该都可以自己动手搞定
4. 有其他的推荐欢迎指出，最好注明在使用和维护上面的优点，以及演示实例的网址，方面 debiancn 用户参与选择
5. 对现在首页的不满意可以具体到哪一点告知一下，我保证我会好好改的 :octocat: 

使用样式库的好处就是，就算不懂设计，做出来的网页也不会很难看 -_-

社区首页的外观最好和社区源主页统一起来， @YanhaoMo 觉得社区源主页的样式看起来还不错，但是软件仓库目录字符串超过移动设备屏幕宽度，还没想好应该怎么做响应式布局，请了解这方面内容的菊苣教教我要这么弄，我觉得最差的方案就是把字符串拆出来再拼回去。

请问一下，有没有功能方面的改进建议阿 :D ，比如说，进入我们的首页，你希望看到哪些内容呢

**Comment by Yanhao** [comment]
支持~ 我这边没有什么问题, 如果你觉得好的话就放手去做好了. 至于首页的样式什么的我也没啥意见, 这个你自己决定就好, 保证现有的内容(文字)都还有就行
