### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by Parrotseccn** [debiancn/debiancn-home#8]
ParrotSecurity是基于Debian的一个专注于渗透测试和隐私保护的发行版
ParrotSec中文社区成立于17年6月份,一直希望能找到更多志同道合的人
希望Debian中文社区可以互加友链，站长课业比较繁忙，会争取在寒假写出一个类似主页的页面并在友链添加Debian中文社区

这是我们的网址:https://parrotsec-china.org

**Comment by hosiet** [comment]
Ack 待处理

**Comment by hosiet** [comment]
已完成
