### ISSUE TITLE
首页设计问题

### ISSUE THREAD

**Issue by yangfl** [debiancn/debiancn-home#9]
* [ ] 中英文之间加空格不统一
* [ ] 相关链接和友情链接行距不统一
* [ ] 导航栏 menuListSelected 不起作用
* [ ] wiki没去除
* [ ] 联系我们 ol 有迷之缩进，手机上会很难看
* [ ] 导航栏的变化最好反应到hash中

**Comment by Yanhao** [comment]
什么时候提的这个issue，我居然没注意 0.0
